const config = window.SMILE_SHIRT_CONFIG || {};
const demoProducts = [
  {sku:"SS-001",name:"เสื้อเชิ้ตวินเทจคละลาย",category:"เสื้อเชิ้ต",price:150,stock:1,status:"พร้อมขาย",mediaType:"รูปภาพ + วิดีโอ",imageUrl:"assets/shop-shirts.jpeg",videoUrl:"assets/demo-shirt-video.mp4",size:"ฟรีไซซ์",color:"คละสี",description:"สินค้ามือสองคัดคุณภาพ แต่ละตัวมีเอกลักษณ์และจำนวนจำกัด"},
  {sku:"SS-002",name:"หมวกแก๊ปวินเทจ",category:"หมวก",price:150,stock:1,status:"พร้อมขาย",mediaType:"รูปภาพเท่านั้น",imageUrl:"assets/shop-caps.jpeg",videoUrl:"",size:"ฟรีไซซ์",color:"คละสี",description:"หมวกมือสองคัดคุณภาพ เลือกสีที่เข้ากับลุคของคุณ"},
  {sku:"SS-003",name:"เสื้อเชิ้ตแขนสั้นคละแบบ",category:"เสื้อเชิ้ต",price:150,stock:1,status:"พร้อมขาย",mediaType:"รูปภาพเท่านั้น",imageUrl:"assets/shop-rack.jpeg",videoUrl:"",size:"ฟรีไซซ์",color:"คละสี",description:"เสื้อเชิ้ตคัดคุณภาพพร้อมส่ง เหมาะกับลุคสบาย ๆ ในทุกวัน"}
];
let products = demoProducts;
let settings = {bankName:"รอเพิ่มข้อมูลจริง",accountNumber:"xxx-x-xxxxx-x",accountName:"รอเพิ่มข้อมูลจริง",qrUrl:"",storeAddress:"ช่างชุ่ย ครีเอทีฟ พาร์ค ถนนสิรินธร แขวงบางพลัด เขตบางพลัด กรุงเทพมหานคร",routeVideoUrl:"",promoImageUrl:"",promoQualityText:"คัดคุณภาพทุกตัว",promoPriceText:"เริ่มต้น ฿120",shippingMinimum:60,codRate:.04,shippingRates:[{minItems:1,maxItems:999,privateFee:60,postFee:60}]};
let cart = JSON.parse(localStorage.getItem("smile-shirt-cart") || "{}");
let selectedProduct = null;
const $ = (s) => document.querySelector(s);
const lastOrder = () => { try { return JSON.parse(localStorage.getItem("smile-shirt-last-order") || "null"); } catch { return null; } };
const money = n => `฿${Number(n || 0).toLocaleString("th-TH",{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const fallbackImage = "assets/shop-shirts.jpeg";

function imageDisplayUrl(value){
  const url=String(value||"").trim();
  if(!url)return "";
  const driveFile=url.match(/drive\.google\.com\/file\/d\/([^/?#]+)/i);
  const driveId=driveFile?.[1]||url.match(/[?&]id=([^&#]+)/i)?.[1];
  return driveId?`https://drive.google.com/thumbnail?id=${encodeURIComponent(driveId)}&sz=w1200`:url;
}

function saveCart(){localStorage.setItem("smile-shirt-cart",JSON.stringify(cart));renderCart();}
function cartRows(){return products.filter(p=>cart[p.sku]>0).map(p=>({...p,qty:Math.min(cart[p.sku],p.stock||1)}));}
function roundUpHalf(value){return Math.ceil((Number(value)||0)*2)/2}
function shippingFeeFor(method,itemCount){if(!method||method==="รับหน้าร้าน")return 0;const rate=(settings.shippingRates||[]).find(r=>itemCount>=Number(r.minItems||1)&&itemCount<=Number(r.maxItems||999));const configured=method==="ไปรษณีย์ไทย"?Number(rate?.postFee):Number(rate?.privateFee);return Math.max(Number(settings.shippingMinimum)||60,configured||0)}
function totals(method=""){const rows=cartRows(),subtotal=rows.reduce((s,p)=>s+p.price*p.qty,0),itemCount=rows.reduce((s,p)=>s+p.qty,0),shippingFee=shippingFeeFor(method,itemCount),codFee=method&&method!=="รับหน้าร้าน"?Math.round((subtotal+shippingFee)*(Number(settings.codRate)||.04)*100)/100:0,total=Math.round((subtotal+shippingFee+codFee)*100)/100,deposit=roundUpHalf(total*.5);return{subtotal,shippingFee,codFee,total,deposit,balance:Math.round((total-deposit)*100)/100,itemCount};}
function showToast(message){const t=$("#toast");t.textContent=message;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),1800)}
function openLayer(el){el.classList.add("open");el.setAttribute("aria-hidden","false");document.body.classList.add("locked")}
function closeLayer(el){el.classList.remove("open");el.setAttribute("aria-hidden","true");if(!document.querySelector(".modal.open,.drawer.open"))document.body.classList.remove("locked")}

function renderProducts(){
  $("#productGrid").innerHTML=products.map((p,i)=>`<button class="product-card" data-product="${p.sku}" type="button">
    <div class="product-image"><img src="${escapeAttr(imageDisplayUrl(p.imageUrl)||fallbackImage)}" alt="${escapeAttr(p.name)}" loading="lazy"><span class="status-badge">${p.stock>0?"พร้อมส่ง":"หมด"}</span><span class="media-badge">${p.videoUrl?"รูป + วิดีโอ":"รูปภาพ"}</span></div>
    <div class="product-copy"><h3>${escapeHtml(p.name)}</h3><p>${escapeHtml(p.category||"แฟชั่นมือสองคัดคุณภาพ")}</p><div class="product-price"><strong>${money(p.price)}</strong><span>ดูสินค้า 0${i+1}</span></div></div>
  </button>`).join("");
  document.querySelectorAll("[data-product]").forEach(b=>b.addEventListener("click",()=>showProduct(b.dataset.product)));
}
function showProduct(sku){selectedProduct=products.find(p=>p.sku===sku);if(!selectedProduct)return;$("#modalProductTag").textContent=selectedProduct.category||"SELECTED FASHION";$("#modalProductName").textContent=selectedProduct.name;$("#modalProductDescription").textContent=selectedProduct.description||"สินค้ามือสองคัดคุณภาพ แต่ละตัวมีเอกลักษณ์และจำนวนจำกัด";$("#modalProductPrice").textContent=money(selectedProduct.price);$("#modalStock").textContent=`เหลือ ${selectedProduct.stock} ชิ้น`;renderModalMedia("image");$("#modalAddButton").disabled=selectedProduct.stock<1;openLayer($("#productModal"))}
function renderModalMedia(type){const p=selectedProduct;if(!p)return;const image=imageDisplayUrl(p.imageUrl)||fallbackImage;let media=type==="video"&&p.videoUrl?`<video src="${escapeAttr(p.videoUrl)}" poster="${escapeAttr(image)}" controls autoplay muted playsinline></video>`:`<img src="${escapeAttr(image)}" alt="${escapeAttr(p.name)}">`;const tabs=p.videoUrl?`<div class="media-tabs"><button class="${type==="image"?"active":""}" data-media="image">รูปภาพ</button><button class="${type==="video"?"active":""}" data-media="video">วิดีโอ</button></div>`:"";$("#modalMedia").innerHTML=media+tabs;document.querySelectorAll("[data-media]").forEach(b=>b.addEventListener("click",()=>renderModalMedia(b.dataset.media)))}
function addToCart(product){if(!product||product.stock<1)return;cart[product.sku]=Math.min((cart[product.sku]||0)+1,product.stock);saveCart();showToast("เพิ่มลงตะกร้าแล้ว")}
function changeQty(sku,delta){const p=products.find(x=>x.sku===sku);cart[sku]=Math.max(0,Math.min((cart[sku]||0)+delta,p?.stock||1));if(!cart[sku])delete cart[sku];saveCart()}
function renderCart(){const rows=cartRows();$("#cartCount").textContent=rows.reduce((s,p)=>s+p.qty,0);$("#cartItems").innerHTML=rows.length?rows.map(p=>`<div class="cart-item"><img src="${escapeAttr(imageDisplayUrl(p.imageUrl)||fallbackImage)}" alt=""><div><h3>${escapeHtml(p.name)}</h3><strong>${money(p.price)}</strong></div><div class="quantity"><button data-qty="-1" data-sku="${p.sku}">−</button><b>${p.qty}</b><button data-qty="1" data-sku="${p.sku}">+</button></div></div>`).join(""):`<div class="empty-cart">ยังไม่มีสินค้าในตะกร้า</div>`;document.querySelectorAll("[data-qty]").forEach(b=>b.addEventListener("click",()=>changeQty(b.dataset.sku,Number(b.dataset.qty))));const t=totals();$("#cartSummary").innerHTML=rows.length?`<div class="summary-row"><span>ยอดสินค้า</span><span>${money(t.subtotal)}</span></div><small>ค่าจัดส่งและค่าบริการเก็บเงินปลายทางจะคำนวณหลังเลือกวิธีรับสินค้า</small><button id="checkoutButton" class="action-button">ดำเนินการสั่งซื้อ</button>`:"";$("#checkoutButton")?.addEventListener("click",openCheckout)}
function renderPaymentInfo(){const method=document.querySelector('input[name="paymentMethod"]:checked')?.value;if(method==="QR Code"&&settings.qrUrl){$("#paymentInfo").innerHTML=`<div class="qr-placeholder"><img src="${escapeAttr(imageDisplayUrl(settings.qrUrl))}" alt="QR Code ชำระเงิน"></div>`}else if(method==="QR Code"){$("#paymentInfo").innerHTML=`<div class="qr-placeholder"><div><b>พื้นที่สำหรับ QR Code</b><small>เพิ่มลิงก์ภาพ QR ใน Google Sheets ภายหลัง</small></div></div>`}else{$("#paymentInfo").innerHTML=`<div class="payment-account"><small>บัญชีสำหรับรับมัดจำ</small><strong class="payment-bank">${escapeHtml(settings.bankName)}</strong><span class="payment-account-number">${escapeHtml(settings.accountNumber)}</span><span class="payment-account-name"><b>ชื่อบัญชี</b>${escapeHtml(settings.accountName)}</span></div>`}}
function renderCheckoutSummary(){const method=$("#checkoutForm").elements.shippingMethod.value,t=totals(method),hasShipping=method&&method!=="รับหน้าร้าน";$("#checkoutDeposit").textContent=money(t.deposit);$("#checkoutSummary").innerHTML=`<div><span>ยอดสินค้า</span><b>${money(t.subtotal)}</b></div><div><span>ค่าจัดส่ง${!method?" (เลือกวิธีรับสินค้า)":""}</span><b>${method?money(t.shippingFee):"—"}</b></div><div><span>ค่าบริการเก็บเงินปลายทาง 4%</span><b>${method?money(t.codFee):"—"}</b></div><div class="checkout-total"><span>ยอดรวมสุทธิ</span><b>${method?money(t.total):"—"}</b></div><div class="transfer-total"><span>ยอดมัดจำที่ต้องโอน 50%</span><b>${method?money(t.deposit):"—"}</b></div>${hasShipping?'<small><b>โปรดโอนตามยอดมัดจำที่ระบบแจ้งเท่านั้น</b> ยอดที่ต้องโอนจะปัดขึ้นเป็น .00 หรือ .50 บาท ส่วนค่าบริการเก็บเงินปลายทาง 4% คำนวณจากยอดสินค้า + ค่าจัดส่ง</small>':method?'<small><b>โปรดโอนตามยอดมัดจำที่ระบบแจ้งเท่านั้น</b> ยอดที่ต้องโอนจะปัดขึ้นเป็น .00 หรือ .50 บาท</small>':''}`}
function openCheckout(){if(!cartRows().length)return;closeLayer($("#cartDrawer"));$("#checkoutForm").elements.shippingMethod.value="";renderCheckoutSummary();renderPaymentInfo();openLayer($("#checkoutModal"))}
async function fileToData(file){if(!file)return null;if(file.size>8*1024*1024)throw new Error("ไฟล์สลิปต้องไม่เกิน 8 MB");return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve({name:file.name,type:file.type,data:String(reader.result).split(",")[1]});reader.onerror=()=>reject(new Error("อ่านไฟล์ไม่สำเร็จ"));reader.readAsDataURL(file)})}
async function submitOrder(e){e.preventDefault();const btn=$("#submitOrderButton"),error=$("#formError");error.textContent="";if(!config.appsScriptUrl){error.textContent="เว็บไซต์ตัวอย่างยังไม่ได้เชื่อม Google Sheets กรุณาตั้งค่า Apps Script ก่อน";return}btn.disabled=true;btn.textContent="กำลังสร้างออร์เดอร์...";try{const form=new FormData(e.currentTarget);if(form.get("website"))throw new Error("ไม่สามารถส่งรายการได้");const slip=await fileToData($("#slipInput").files[0]);const payload={action:"createOrder",customerName:form.get("customerName"),phone:form.get("phone"),shippingMethod:form.get("shippingMethod"),address:form.get("address"),paymentMethod:form.get("paymentMethod"),items:cartRows().map(p=>({sku:p.sku,quantity:p.qty})),slip};const response=await fetch(config.appsScriptUrl,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(payload),redirect:"follow"});const result=await response.json();if(!result.ok)throw new Error(result.error||"สร้างออร์เดอร์ไม่สำเร็จ");$("#successOrderNumber").textContent=result.orderNumber;localStorage.setItem("smile-shirt-last-order",JSON.stringify({orderNumber:result.orderNumber,phone:String(form.get("phone")||"")}));renderLastOrderNotice();$("#checkoutFormView").hidden=true;$("#orderSuccess").hidden=false;cart={};saveCart()}catch(err){error.textContent=err.message||"เกิดข้อผิดพลาด กรุณาลองใหม่"}finally{btn.disabled=false;btn.textContent="ยืนยันและส่งหลักฐาน"}}
function renderPromotion(){const image=$("#heroPromoImage");if(settings.promoImageUrl)image.src=imageDisplayUrl(settings.promoImageUrl);$("#heroQualityChip").textContent=settings.promoQualityText||"คัดคุณภาพทุกตัว";$("#heroPriceChip").textContent=settings.promoPriceText||"เริ่มต้น ฿120"}
function renderLastOrderNotice(){const saved=lastOrder(),notice=$("#lastOrderNotice");if(!saved?.orderNumber){notice.hidden=true;return}notice.hidden=false;notice.innerHTML=`<div><b>หมายเลขออร์เดอร์ล่าสุด: ${escapeHtml(saved.orderNumber)}</b><small>กรุณาเก็บหมายเลขนี้ไว้สำหรับติดตามคำสั่งซื้อ</small></div><button type="button">ใช้หมายเลขนี้</button>`;notice.querySelector("button").addEventListener("click",()=>{const form=$("#trackingForm");form.elements.orderNumber.value=saved.orderNumber;form.elements.phone.value=saved.phone||""})}
async function copyOrderNumber(){const number=$("#successOrderNumber").textContent.trim();if(!number)return;try{await navigator.clipboard.writeText(number);showToast("คัดลอกหมายเลขออร์เดอร์แล้ว")}catch{showToast(`กรุณาบันทึก ${number}`)}}
async function loadData(){if(!config.appsScriptUrl){renderPromotion();renderProducts();renderCart();return}try{const response=await fetch(`${config.appsScriptUrl}?action=store`,{redirect:"follow"});const data=await response.json();if(data.products?.length)products=data.products;if(data.settings)settings={...settings,...data.settings};$("#storeAddress").textContent=settings.storeAddress||$("#storeAddress").textContent;renderPromotion();renderRouteVideo();renderProducts();renderCart()}catch{renderPromotion();renderProducts();renderCart();showToast("กำลังแสดงสินค้าตัวอย่าง")}}
function renderRouteVideo(){if(!settings.routeVideoUrl)return;const url=settings.routeVideoUrl;$("#routeVideoBox").classList.remove("empty");if(/youtube\.com|youtu\.be/.test(url)){const id=(url.match(/(?:youtu\.be\/|v=|embed\/)([^?&/]+)/)||[])[1];if(id)$("#routeVideoBox").innerHTML=`<iframe src="https://www.youtube.com/embed/${encodeURIComponent(id)}" title="วิดีโอแนะนำทางมาร้าน" allowfullscreen></iframe>`}else{$("#routeVideoBox").innerHTML=`<video src="${escapeAttr(url)}" controls playsinline></video>`}}
async function trackOrder(e){e.preventDefault();const result=$("#trackingResult"),form=new FormData(e.currentTarget),orderNumber=String(form.get("orderNumber")||"").trim().toUpperCase(),phone=String(form.get("phone")||"").trim();result.innerHTML="<p>กำลังตรวจสอบ...</p>";if(!config.appsScriptUrl){result.innerHTML='<p class="tracking-error">ระบบติดตามยังไม่ได้เชื่อม Google Sheets</p>';return}try{const params=new URLSearchParams({action:"track",orderNumber,phone});const response=await fetch(`${config.appsScriptUrl}?${params}`,{redirect:"follow"});const data=await response.json();if(!data.ok)throw new Error(data.error||"ไม่พบคำสั่งซื้อ");result.innerHTML=`<div class="tracking-card"><div><small>เลขออร์เดอร์</small><strong>${escapeHtml(data.orderNumber)}</strong></div><div><small>การชำระเงิน</small><strong>${escapeHtml(data.paymentStatus)}</strong></div><div><small>สถานะจัดส่ง</small><strong>${escapeHtml(data.fulfillmentStatus)}</strong></div><div class="tracking-number"><small>เลขพัสดุ</small><strong>${escapeHtml(data.trackingNumber||"ร้านยังไม่ได้เพิ่มเลขพัสดุ")}</strong></div></div>`}catch(err){result.innerHTML=`<p class="tracking-error">${escapeHtml(err.message||"ตรวจสอบข้อมูลไม่สำเร็จ")}</p>`}}
function escapeHtml(v=""){return String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
function escapeAttr(v=""){return escapeHtml(v)}
$("#cartButton").addEventListener("click",()=>openLayer($("#cartDrawer")));$("#modalAddButton").addEventListener("click",()=>addToCart(selectedProduct));$("#checkoutForm").addEventListener("submit",submitOrder);$("#checkoutForm").elements.shippingMethod.addEventListener("change",renderCheckoutSummary);$("#trackingForm").addEventListener("submit",trackOrder);$("#copyOrderNumber").addEventListener("click",copyOrderNumber);$("#slipInput").addEventListener("change",e=>$("#fileName").textContent=e.target.files[0]?.name||"JPG, PNG, WEBP หรือ PDF ไม่เกิน 8 MB");$("[data-track-order]").addEventListener("click",()=>closeLayer($("#checkoutModal")));document.querySelectorAll('input[name="paymentMethod"]').forEach(r=>r.addEventListener("change",renderPaymentInfo));document.querySelectorAll("[data-close]").forEach(b=>b.addEventListener("click",()=>{const type=b.dataset.close;closeLayer(type==="cart"?$("#cartDrawer"):type==="product"?$("#productModal"):$("#checkoutModal"));if(type==="checkout"&&lastOrder()?.orderNumber)showToast("อย่าลืมบันทึกหมายเลขออร์เดอร์สำหรับติดตามสินค้า")}));document.addEventListener("keydown",e=>{if(e.key==="Escape")document.querySelectorAll(".modal.open,.drawer.open").forEach(closeLayer)});renderLastOrderNotice();loadData();
